//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyBill.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBillService")]
    public interface IBillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetBill", ReplyAction="http://tempuri.org/IBillService/GetBillResponse")]
        string GetBill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetBill", ReplyAction="http://tempuri.org/IBillService/GetBillResponse")]
        System.Threading.Tasks.Task<string> GetBillAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillServiceChannel : SkyBill.ServiceReference1.IBillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServiceClient : System.ServiceModel.ClientBase<SkyBill.ServiceReference1.IBillService>, SkyBill.ServiceReference1.IBillService {
        
        public BillServiceClient() {
        }
        
        public BillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBill() {
            return base.Channel.GetBill();
        }
        
        public System.Threading.Tasks.Task<string> GetBillAsync() {
            return base.Channel.GetBillAsync();
        }
    }
}
